from __future__ import annotations

import argparse
import base64
import json
import os
import shlex
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol


ONE_BY_ONE_PNG = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wn3l7cAAAAASUVORK5CYII="
)


@dataclass(frozen=True)
class JobSpec:
    job_id: str
    user_id: str
    companion_id: str | None
    name: str
    base_model: str
    trigger_word: str
    training_steps: int
    dataset_dir: Path
    dataset_urls: list[str]
    output_dir: Path
    metadata: dict[str, Any]

    @classmethod
    def from_path(cls, path: Path) -> JobSpec:
        payload = json.loads(path.read_text(encoding="utf-8"))
        return cls(
            job_id=payload["job_id"],
            user_id=payload["user_id"],
            companion_id=payload.get("companion_id"),
            name=payload["name"],
            base_model=payload["base_model"],
            trigger_word=payload["trigger_word"],
            training_steps=int(payload["training_steps"]),
            dataset_dir=Path(payload["dataset_dir"]),
            dataset_urls=list(payload.get("dataset_urls") or []),
            output_dir=Path(payload["output_dir"]),
            metadata=dict(payload.get("metadata") or {}),
        )


@dataclass(frozen=True)
class ProviderResult:
    status: str
    progress_pct: int
    provider_job_id: str | None = None
    weights_path: str | None = None
    adapter_path: str | None = None
    model_path: str | None = None
    preview_path: str | None = None
    error_message: str | None = None
    metadata: dict[str, Any] | None = None
    result: dict[str, Any] | None = None

    def to_dict(self) -> dict[str, Any]:
        payload = {
            "status": self.status,
            "progress_pct": self.progress_pct,
            "provider_job_id": self.provider_job_id,
            "weights_path": self.weights_path,
            "adapter_path": self.adapter_path,
            "model_path": self.model_path,
            "preview_path": self.preview_path,
            "error_message": self.error_message,
            "metadata": self.metadata or {},
            "result": self.result or {},
        }
        return {key: value for key, value in payload.items() if value is not None}


class TrainerProvider(Protocol):
    name: str
    description: str

    def run(self, job_spec: JobSpec, result_path: Path) -> ProviderResult:
        ...


class MockImageLoraProvider:
    name = "mock-image-lora"
    description = "Create placeholder LoRA artifacts for smoke tests."

    def run(self, job_spec: JobSpec, result_path: Path) -> ProviderResult:
        job_spec.output_dir.mkdir(parents=True, exist_ok=True)
        weights_path = job_spec.output_dir / f"{job_spec.job_id}.safetensors"
        preview_path = job_spec.output_dir / f"{job_spec.job_id}_preview.png"

        weights_payload = {
            "job_id": job_spec.job_id,
            "user_id": job_spec.user_id,
            "base_model": job_spec.base_model,
            "trigger_word": job_spec.trigger_word,
            "training_steps": job_spec.training_steps,
            "dataset_count": len(job_spec.dataset_urls),
            "note": "placeholder safetensors file generated by mock-image-lora",
        }
        weights_path.write_text(json.dumps(weights_payload, indent=2), encoding="utf-8")
        preview_path.write_bytes(ONE_BY_ONE_PNG)

        return ProviderResult(
            status="completed",
            progress_pct=100,
            provider_job_id=f"mock-{job_spec.job_id}",
            weights_path=str(weights_path),
            preview_path=str(preview_path),
            metadata={
                "provider": self.name,
                "modality": "image",
                "job_family": "training.lora",
                "scaffold": True,
            },
            result={
                "provider_family": "training.lora.image",
                "base_model": job_spec.base_model,
                "artifact_format": "safetensors",
                "preview_format": "png",
            },
        )


class ExternalCommandProvider:
    def __init__(self, name: str, env_var: str, description: str) -> None:
        self.name = name
        self.env_var = env_var
        self.description = description

    def run(self, job_spec: JobSpec, result_path: Path) -> ProviderResult:
        command_text = os.getenv(self.env_var, "").strip()
        if not command_text:
            raise RuntimeError(f"{self.env_var} is not configured")

        command = shlex.split(command_text) + [
            "--job-spec",
            str(job_spec_path(job_spec)),
            "--result-path",
            str(result_path),
        ]
        completed = subprocess.run(command, check=False, capture_output=True, text=True)
        if completed.returncode != 0:
            error_text = completed.stderr.strip() or completed.stdout.strip() or "External trainer failed"
            return ProviderResult(status="dead_letter", progress_pct=0, error_message=error_text)
        if not result_path.exists():
            return ProviderResult(
                status="dead_letter",
                progress_pct=0,
                error_message="External trainer completed without writing a result manifest",
            )
        payload = json.loads(result_path.read_text(encoding="utf-8"))
        return ProviderResult(
            status=payload.get("status", "completed"),
            progress_pct=int(payload.get("progress_pct", 100)),
            provider_job_id=payload.get("provider_job_id"),
            weights_path=payload.get("weights_path"),
            adapter_path=payload.get("adapter_path"),
            model_path=payload.get("model_path"),
            preview_path=payload.get("preview_path"),
            error_message=payload.get("error_message"),
            metadata=dict(payload.get("metadata") or {}),
            result=dict(payload.get("result") or {}),
        )


def job_spec_path(job_spec: JobSpec) -> Path:
    return job_spec.output_dir.parent / "job-spec.json"


def resolve_provider_name(job_spec: JobSpec, explicit_provider: str | None) -> str:
    if explicit_provider:
        return explicit_provider
    metadata = job_spec.metadata
    return (
        metadata.get("trainer_provider")
        or metadata.get("provider_key")
        or os.getenv("SELF_LORA_TRAINER_PROVIDER", "mock-image-lora")
    )


def provider_registry() -> dict[str, TrainerProvider]:
    return {
        "mock-image-lora": MockImageLoraProvider(),
        "external-command": ExternalCommandProvider(
            "external-command",
            "SELF_LORA_IMAGE_LORA_COMMAND",
            "Backward-compatible alias for the image external trainer wrapper.",
        ),
        "external-image-command": ExternalCommandProvider(
            "external-image-command",
            "SELF_LORA_IMAGE_LORA_COMMAND",
            "Delegate image LoRA jobs to the configured image wrapper command.",
        ),
        "external-video-command": ExternalCommandProvider(
            "external-video-command",
            "SELF_LORA_VIDEO_LORA_COMMAND",
            "Delegate video LoRA jobs to the configured video wrapper command.",
        ),
    }


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Provider router for self-lora trainer jobs.")
    parser.add_argument("--job-spec", type=Path, help="Path to the normalized trainer job spec JSON.")
    parser.add_argument("--result-path", type=Path, help="Path where the result manifest must be written.")
    parser.add_argument("--provider", type=str, default=None, help="Explicit provider name override.")
    parser.add_argument("--list-providers", action="store_true", help="List available providers and exit.")
    return parser.parse_args(argv)


def write_result(result_path: Path, result: ProviderResult) -> None:
    result_path.parent.mkdir(parents=True, exist_ok=True)
    result_path.write_text(json.dumps(result.to_dict(), indent=2), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    providers = provider_registry()

    if args.list_providers:
        payload = {
            name: {"description": provider.description}
            for name, provider in sorted(providers.items())
        }
        print(json.dumps(payload, indent=2))
        return 0

    if args.job_spec is None or args.result_path is None:
        raise SystemExit("--job-spec and --result-path are required unless --list-providers is used")

    job_spec = JobSpec.from_path(args.job_spec)
    provider_name = resolve_provider_name(job_spec, args.provider)
    provider = providers.get(provider_name)
    if provider is None:
        write_result(
            args.result_path,
            ProviderResult(
                status="dead_letter",
                progress_pct=0,
                error_message=f"Unknown trainer provider '{provider_name}'",
                metadata={"available_providers": sorted(providers)},
            ),
        )
        return 2

    try:
        result = provider.run(job_spec, args.result_path)
    except Exception as exc:
        write_result(
            args.result_path,
            ProviderResult(
                status="dead_letter",
                progress_pct=0,
                error_message=str(exc),
                metadata={"provider": provider_name},
            ),
        )
        return 1

    write_result(args.result_path, result)
    return 0 if result.status != "dead_letter" else 1


if __name__ == "__main__":
    raise SystemExit(main())
